// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnfW8Djuc9ueQypypcvTmwOYMboGmw_KU',
    appId: '1:732236478064:web:ee7236c598824719eb66b5',
    messagingSenderId: '732236478064',
    projectId: 'fireauth1wqeda',
    authDomain: 'fireauth1wqeda.firebaseapp.com',
    storageBucket: 'fireauth1wqeda.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCruIfaa73C266PTi91Gb7pISBR3WnEX4A',
    appId: '1:732236478064:android:fc8ef7afe9c57465eb66b5',
    messagingSenderId: '732236478064',
    projectId: 'fireauth1wqeda',
    storageBucket: 'fireauth1wqeda.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA43-EAYV0ygYtKc37m1rHudsNwpAE6FUE',
    appId: '1:732236478064:ios:454396522b70e157eb66b5',
    messagingSenderId: '732236478064',
    projectId: 'fireauth1wqeda',
    storageBucket: 'fireauth1wqeda.appspot.com',
    iosClientId: '732236478064-pm4sb2qen95voafvolpq406uc0kbnbav.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireauth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA43-EAYV0ygYtKc37m1rHudsNwpAE6FUE',
    appId: '1:732236478064:ios:454396522b70e157eb66b5',
    messagingSenderId: '732236478064',
    projectId: 'fireauth1wqeda',
    storageBucket: 'fireauth1wqeda.appspot.com',
    iosClientId: '732236478064-pm4sb2qen95voafvolpq406uc0kbnbav.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireauth',
  );
}
